[project]
name = "aa-system-monitor-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash>=2.18.2",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "psutil>=6.1.1",
]
